### PR TITLE
fix missing changelog entries

### PR DESCRIPTION
**Pull request by AGS4NO**
Changelog updates from github-changelog-generator have been overwriting the existing version since v3.3.0 due to missing tags in the release process.

- Fixes changelog entries for versions >= 3.3.0

This PR represent all of the release process tasks excluding the release commit and publish to supermarket.

## Tasks

- [x] Tag all previous release commits
  - [x] `git tag <tag-name> <commit-sha>`
  - [x] `git push origin <tag-name>`
- [ ] Verify github-changelog-generator output
- [ ] Verify commit, tag, and supermarket commands

### CODE REVIEW

**Review by DXTimer — CHANGES_REQUESTED** [review]
We have a more human-centric changelog format that focuses on the important parts for the dependants' maintainers. Please check it out in the internal wiki.

**Comment by AGS4NO** [comment]
> We have a more human-centric changelog format that focuses on the important parts for the dependants' maintainers. Please check it out in the internal wiki.

I feel that this should be part of separate issue if we want to modify the format of the changelog:
1. This change impacts all public cookbook releases (dnsimple and pdns)
2. This moves an existing process which is automated to a manual one

**Review by san983 — APPROVED** [review]

**Review by onlyhavecans — APPROVED** [review]
I concur that this is addressing a fix in the current and changing the documented cookbook workflow is a separate policy change.

**Comment by DXTimer** [comment]
> I concur that this is addressing a fix in the current and changing the documented cookbook workflow is a separate policy change.

I agree in which case a cookbook version bump should not happen as part of this PR.

**Comment by AGS4NO** [comment]
> I agree in which case a cookbook version bump should not happen as part of this PR.

I removed the version change from this PR and will bump as part of a release commit after testing the fixes for change log generation.

**Pull request merged**
